function dq_itu = dq_itu_Voltra(U1,U2,U3,U4,a,l,m,m_sat,px,py,pz,q1,q2,q3,q4)
%DQ_ITU_VOLTRA
%    DQ_ITU = DQ_ITU_VOLTRA(U1,U2,U3,U4,A,L,M,M_SAT,PX,PY,PZ,Q1,Q2,Q3,Q4)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    07-Oct-2020 07:02:58

t2 = cos(q3);
t3 = sin(q3);
t4 = cos(q2);
t5 = 1.0./t4;
t6 = sin(q2);
t7 = m+m_sat;
t8 = 1.0./t7;
t9 = sin(q1);
t10 = cos(q1);
t11 = a.*2.0;
t12 = q4.*2.0;
t13 = l+t11+t12;
dq_itu = [t5.*(U2.*t3+U3.*t2);U2.*t2-U3.*t3;t5.*(U1.*t4+U2.*t3.*t6+U3.*t2.*t6);U4;px.*t8-U4.*m.*t8.*(t3.*t9+t2.*t6.*t10)-U1.*m.*t8.*t13.*(t2.*t9-t3.*t6.*t10).*(1.0./2.0)-U2.*m.*t4.*t8.*t10.*t13.*(1.0./2.0);py.*t8+U4.*m.*t8.*(t3.*t10-t2.*t6.*t9)+U1.*m.*t8.*t13.*(t2.*t10+t3.*t6.*t9).*(1.0./2.0)-U2.*m.*t4.*t8.*t9.*t13.*(1.0./2.0);pz.*t8-U4.*m.*t2.*t4.*t8+U2.*m.*t6.*t8.*t13.*(1.0./2.0)+U1.*m.*t3.*t4.*t8.*t13.*(1.0./2.0)];
