function T = Energy(Ixx,Ixy,Ixz,Iyy,Iyz,Izz,U1,U2,U3,U4,a,l,m,m_sat,px,py,pz,q1,q2,q3,q4)
%ENERGY
%    T = ENERGY(IXX,IXY,IXZ,IYY,IYZ,IZZ,U1,U2,U3,U4,A,L,M,M_SAT,PX,PY,PZ,Q1,Q2,Q3,Q4)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    07-Oct-2020 07:02:55

t2 = m+m_sat;
t3 = 1.0./t2;
t4 = sin(q1);
t5 = sin(q3);
t6 = t4.*t5;
t7 = cos(q1);
t8 = cos(q3);
t9 = sin(q2);
t10 = t7.*t8.*t9;
t11 = t6+t10;
t12 = a.*2.0;
t13 = q4.*2.0;
t14 = l+t12+t13;
t15 = t5.*t7;
t33 = t4.*t8.*t9;
t16 = t15-t33;
t17 = cos(q2);
t19 = pz.*t3;
t20 = U4.*m.*t3.*t8.*t17;
t21 = U2.*m.*t3.*t9.*t14.*(1.0./2.0);
t22 = U1.*m.*t3.*t5.*t14.*t17.*(1.0./2.0);
t23 = t19-t20+t21+t22;
t24 = px.*t3;
t25 = U4.*m.*t3.*t11;
t26 = t4.*t8;
t27 = t5.*t7.*t9;
t28 = t26-t27;
t29 = U1.*m.*t3.*t14.*t28.*(1.0./2.0);
t30 = U2.*m.*t3.*t7.*t14.*t17.*(1.0./2.0);
t31 = -t24+t25+t29+t30;
t32 = py.*t3;
t34 = U4.*m.*t3.*t16;
t35 = t7.*t8;
t36 = t4.*t5.*t9;
t37 = t35+t36;
t38 = U1.*m.*t3.*t14.*t37.*(1.0./2.0);
t39 = U2.*m.*t3.*t4.*t14.*t17.*(1.0./2.0);
t40 = t32+t34+t38-t39;
t43 = t11.*t31;
t44 = t16.*t40;
t45 = t8.*t17.*t23;
t18 = U4-t43-t44+t45;
t41 = t9.*t23+t7.*t17.*t31-t4.*t17.*t40;
t42 = U2.*t14-t9.*t23.*2.0-t7.*t17.*t31.*2.0+t4.*t17.*t40.*2.0;
t46 = t43+t44-t45;
t47 = t28.*t31+t37.*t40+t5.*t17.*t23;
t48 = -U1.*t14+t28.*t31.*2.0+t37.*t40.*2.0+t5.*t17.*t23.*2.0;
T = U1.*(-Ixx.*U1+Ixy.*U2+Ixz.*U3).*(-1.0./2.0)-U2.*(Ixy.*U1-Iyy.*U2+Iyz.*U3).*(1.0./2.0)-U3.*(Ixz.*U1+Iyz.*U2-Izz.*U3).*(1.0./2.0)+m.*t18.^2.*(1.0./2.0)+m.*t42.^2.*(1.0./8.0)+m.*t48.^2.*(1.0./8.0)+m_sat.*t41.^2.*(1.0./2.0)+m_sat.*t46.^2.*(1.0./2.0)+m_sat.*t47.^2.*(1.0./2.0);
