function M21 = M21_Voltra(a,l,m,q1,q2,q3,q4)
%M21_VOLTRA
%    M21 = M21_VOLTRA(A,L,M,Q1,Q2,Q3,Q4)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    07-Oct-2020 07:02:59

t2 = sin(q2);
t3 = cos(q1);
t4 = cos(q2);
t5 = sin(q3);
t6 = l.*(1.0./2.0);
t7 = a+q4+t6;
t8 = cos(q3);
t9 = sin(q1);
t10 = t8.*t9;
t11 = t10-t2.*t3.*t5;
t12 = t4.^2;
t13 = t3.*t8;
t14 = t2.*t5.*t9;
t15 = t13+t14;
M21 = reshape([-m.*t2.*t7.*t11+m.*t3.*t5.*t7.*t12,m.*t2.*t7.*t15+m.*t5.*t7.*t9.*t12,0.0,m.*t3.*t4.*t7.*t8,m.*t4.*t7.*t8.*t9,-m.*t2.*t7.*t8,m.*t7.*t11,-m.*t7.*t15,-m.*t4.*t5.*t7,m.*(t5.*t9.*2.0+t2.*t3.*t8.*2.0).*(1.0./2.0),m.*(t3.*t5.*2.0-t2.*t8.*t9.*2.0).*(-1.0./2.0),m.*t4.*t8],[3,4]);
