function M22 = M22_Voltra(m,m_sat,q1,q2,q3)
%M22_VOLTRA
%    M22 = M22_VOLTRA(M,M_SAT,Q1,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    07-Oct-2020 07:03:00

t3 = cos(q3);
t4 = sin(q1);
t5 = cos(q1);
t6 = sin(q2);
t7 = sin(q3);
t9 = t4.*t7;
t10 = t3.*t5.*t6;
t2 = t9+t10;
t12 = t3.*t4;
t13 = t5.*t6.*t7;
t8 = t12-t13;
t11 = t2.^2;
t14 = t8.^2;
t15 = cos(q2);
t16 = t5.^2;
t17 = t15.^2;
t18 = t3.*t5;
t19 = t4.*t6.*t7;
t20 = t18+t19;
t21 = t5.*t7;
t23 = t3.*t4.*t6;
t22 = t21-t23;
t24 = m.*t4.*t5.*t17;
t25 = m_sat.*t4.*t5.*t17;
t26 = t24+t25-m.*t2.*t22-m.*t8.*t20-m_sat.*t2.*t22-m_sat.*t8.*t20;
t27 = t20.^2;
t28 = t22.^2;
t29 = t4.^2;
t30 = m.*t2.*t3.*t15;
t31 = m_sat.*t2.*t3.*t15;
t32 = t30+t31-m.*t5.*t6.*t15-m.*t7.*t8.*t15-m_sat.*t5.*t6.*t15-m_sat.*t7.*t8.*t15;
t33 = m.*t7.*t15.*t20;
t34 = m_sat.*t7.*t15.*t20;
t35 = t33+t34-m.*t4.*t6.*t15-m.*t3.*t15.*t22-m_sat.*t4.*t6.*t15-m_sat.*t3.*t15.*t22;
t36 = t6.^2;
t37 = t3.^2;
t38 = t7.^2;
M22 = reshape([m.*t11+m.*t14+m_sat.*t11+m_sat.*t14+m.*t16.*t17+m_sat.*t16.*t17,t26,t32,t26,m.*t27+m.*t28+m_sat.*t27+m_sat.*t28+m.*t17.*t29+m_sat.*t17.*t29,t35,t32,t35,m.*t36+m_sat.*t36+m.*t17.*t37+m.*t17.*t38+m_sat.*t17.*t37+m_sat.*t17.*t38],[3,3]);
