function A_ = MassMat(Ixx,Ixy,Ixz,Iyy,Iyz,Izz,a,l,m,m_sat,q4)
%MASSMAT
%    A_ = MASSMAT(IXX,IXY,IXZ,IYY,IYZ,IZZ,A,L,M,M_SAT,Q4)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    07-Oct-2020 07:02:57

t2 = m+m_sat;
t3 = 1.0./t2;
t4 = l.^2;
t5 = m.*m_sat.*t4;
t6 = q4.^2;
t7 = m.*m_sat.*t6.*4.0;
t8 = a.^2;
t9 = m.*m_sat.*t8.*4.0;
t10 = a.*l.*m.*m_sat.*4.0;
t11 = a.*m.*m_sat.*q4.*8.0;
t12 = l.*m.*m_sat.*q4.*4.0;
A_ = reshape([t3.*(t5+t7+t9+t10+t11+t12+Ixx.*m.*4.0+Ixx.*m_sat.*4.0).*(1.0./4.0),-Ixy,-Ixz,0.0,-Ixy,t3.*(t5+t7+t9+t10+t11+t12+Iyy.*m.*4.0+Iyy.*m_sat.*4.0).*(1.0./4.0),-Iyz,0.0,-Ixz,-Iyz,Izz,0.0,0.0,0.0,0.0,m.*m_sat.*t3],[4,4]);
