function Pow = Power(F,U1,U2,U3,U4,q2,q3,tau1,tau2,tau3)
%POWER
%    POW = POWER(F,U1,U2,U3,U4,Q2,Q3,TAU1,TAU2,TAU3)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    07-Oct-2020 07:03:00

t2 = sin(q3);
t3 = cos(q3);
t4 = cos(q2);
t5 = 1.0./t4;
t6 = sin(q2);
t7 = t2.*tau3;
t8 = t7-t3.*tau2;
t9 = t3.*t4.*tau3;
t10 = t2.*t4.*tau2;
t11 = t9+t10-t6.*tau1;
Pow = U1.*tau1+U2.*(-t3.*t8+t2.*t5.*t11+t2.*t5.*t6.*tau1)+U3.*(t2.*t8+t3.*t5.*t11+t3.*t5.*t6.*tau1)+F.*U4;
