function PXYZ = PXYZ_Voltra(a,dq1,dq2,dq3,dq4,dq5,dq6,dq7,l,m,m_sat,q1,q2,q3,q4)
%PXYZ_VOLTRA
%    PXYZ = PXYZ_VOLTRA(A,DQ1,DQ2,DQ3,DQ4,DQ5,DQ6,DQ7,L,M,M_SAT,Q1,Q2,Q3,Q4)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    07-Oct-2020 07:02:59

t2 = sin(q1);
t3 = sin(q3);
t4 = t2.*t3;
t5 = cos(q1);
t6 = cos(q3);
t7 = sin(q2);
t8 = t5.*t6.*t7;
t9 = t4+t8;
t10 = t2.*t6;
t24 = t3.*t5.*t7;
t11 = t10-t24;
t12 = cos(q2);
t13 = l.*(1.0./2.0);
t14 = a+q4+t13;
t15 = t3.*t5;
t18 = t2.*t6.*t7;
t16 = t15-t18;
t17 = dq5.*t9;
t19 = dq7.*t6.*t12;
t40 = dq6.*t16;
t20 = dq4+t17+t19-t40;
t21 = t5.*t6;
t22 = t2.*t3.*t7;
t23 = t21+t22;
t25 = dq5.*t11;
t38 = dq1.*t7;
t26 = dq3-t38;
t27 = t14.*t26;
t37 = dq6.*t23;
t39 = dq7.*t3.*t12;
t28 = t25+t27-t37-t39;
t29 = dq2.*t6;
t30 = dq1.*t3.*t12;
t31 = t29+t30;
t32 = t14.*t31;
t33 = dq5.*t5.*t12;
t34 = dq6.*t2.*t12;
t36 = dq7.*t7;
t35 = t32+t33+t34-t36;
PXYZ = [dq5.*m_sat+m.*(t9.*t20+t11.*t28+t5.*t12.*t35);dq6.*m_sat-m.*(t16.*t20+t23.*t28-t2.*t12.*t35);dq7.*m_sat-m.*(t7.*t35-t6.*t12.*t20+t3.*t12.*t28)];
