function out1 = U_NI(dq1,dq2,dq3,dq4,q2,q3)
%U_NI
%    OUT1 = U_NI(DQ1,DQ2,DQ3,DQ4,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    07-Oct-2020 07:02:58

t2 = sin(q3);
t3 = cos(q2);
t4 = cos(q3);
out1 = [dq3-dq1.*sin(q2);dq2.*t4+dq1.*t2.*t3;-dq2.*t2+dq1.*t3.*t4;dq4];
