function Ptot = Lmom_Maggie(dq1,dq2,dq3,l,m1,m2,q1,q2)
%LMOM_MAGGIE
%    PTOT = LMOM_MAGGIE(DQ1,DQ2,DQ3,L,M1,M2,Q1,Q2)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    05-Oct-2020 08:20:54

t2 = cos(q1);
t3 = sin(q1);
Ptot = [dq3.*m1+m2.*(dq3+dq1.*l.*t2.*(1.0./2.0))+m2.*(dq3+dq2.*l.*cos(q2).*(1.0./2.0)+dq1.*l.*t2);m2.*(dq2.*l.*sin(q2).*(1.0./2.0)+dq1.*l.*t3)+dq1.*l.*m2.*t3.*(1.0./2.0);0.0];
