function Q = GenForce(F,q2,q3,tau1,tau2,tau3)
%GENFORCE
%    Q = GENFORCE(F,Q2,Q3,TAU1,TAU2,TAU3)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    27-Sep-2020 22:01:58

t2 = cos(q2);
t3 = cos(q3);
t4 = sin(q3);
Q = [-tau1.*sin(q2)+t2.*t3.*tau3+t2.*t4.*tau2;t3.*tau2-t4.*tau3;tau1;F;0.0;0.0;0.0];
