function f = constraints(dq1,dq2,l,q1,q2)
%CONSTRAINTS
%    F = CONSTRAINTS(DQ1,DQ2,L,Q1,Q2)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    04-Oct-2020 20:58:08

f = l.*(dq2+dq1.*cos(q1-q2));
