function dq_itu = dq_itu_Gibbs(U1,U2,q1,q2)
%DQ_ITU_GIBBS
%    DQ_ITU = DQ_ITU_GIBBS(U1,U2,Q1,Q2)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    04-Oct-2020 20:58:09

t2 = q1-q2;
t3 = cos(t2);
t4 = t3+1.0;
t5 = 1.0./t4;
dq_itu = [U1.*t5;-U1.*t3.*t5;U2];
