function E = Energy_Gibbs_u(U1,U2,g,l,m1,m2,q1,q2)
%ENERGY_GIBBS_U
%    E = ENERGY_GIBBS_U(U1,U2,G,L,M1,M2,Q1,Q2)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    03-Oct-2020 19:50:19

t2 = U2.^2;
t3 = cos(q1);
t4 = U1.^2;
t5 = l.^2;
t6 = q1-q2;
t7 = cos(t6);
t8 = t7+1.0;
t9 = 1.0./t8.^2;
t10 = cos(q2);
t11 = 1.0./t8;
E = m1.*t2.*(1.0./2.0)+m2.*t2-g.*m2.*(l.*t3+l.*t10.*(1.0./2.0))-g.*l.*m1-g.*l.*m2.*t3.*(1.0./2.0)+m2.*t4.*t5.*t9.*(2.0./3.0)-m2.*t4.*t5.*t7.^2.*t9.*(1.0./3.0)+U1.*U2.*l.*m2.*t3.*t11.*(3.0./2.0)-U1.*U2.*l.*m2.*t7.*t10.*t11.*(1.0./2.0);
