function E = Energy_Gibbs(U1,U2,g,l,m1,m2,q1,q2)
%ENERGY_GIBBS
%    E = ENERGY_GIBBS(U1,U2,G,L,M1,M2,Q1,Q2)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    04-Oct-2020 20:58:08

t2 = U2.^2;
t3 = q1-q2;
t4 = cos(t3);
t5 = q1.*2.0;
t8 = q2.*2.0;
t6 = t5-t8;
t7 = cos(t6);
t9 = U1.^2;
t10 = l.^2;
t11 = cos(q1);
t12 = cos(q2);
E = (m1.*t2.*(3.0./2.0)+m2.*t2.*3.0+m1.*t2.*t4.*2.0+m2.*t2.*t4.*4.0+m1.*t2.*t7.*(1.0./2.0)+m2.*t2.*t7+m2.*t9.*t10-m2.*t7.*t9.*t10.*(1.0./3.0)+U1.*U2.*l.*m2.*t11.*(5.0./2.0)+U1.*U2.*l.*m2.*t12+U1.*U2.*l.*m2.*cos(-q2+t5).*(5.0./4.0)-U1.*U2.*l.*m2.*cos(q1-t8).*(1.0./2.0)-U1.*U2.*l.*m2.*cos(q2.*-3.0+t5).*(1.0./4.0))./(t4.*4.0+t7+3.0)-g.*l.*m1-g.*l.*m2.*t11.*(1.0./2.0)-g.*l.*m2.*(t11.*2.0+t12).*(1.0./2.0);
