function Ptot_u = ptot_Gibbs_u(U1,U2,l,m1,m2,q1,q2)
%PTOT_GIBBS_U
%    PTOT_U = PTOT_GIBBS_U(U1,U2,L,M1,M2,Q1,Q2)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    04-Oct-2020 20:58:09

t2 = q1-q2;
t3 = cos(t2);
t4 = t3+1.0;
t5 = 1.0./t4;
t6 = cos(q1);
t7 = q1-q2.*2.0;
t8 = sin(q1);
Ptot_u = [U2.*m1+m2.*(U2+U1.*l.*t5.*t6.*(1.0./2.0))+m2.*t5.*(U2.*4.0+U2.*t3.*4.0+U1.*l.*t6.*3.0-U1.*l.*cos(t7)).*(1.0./4.0);U1.*l.*m2.*t5.*(t8.*3.0+sin(t7)).*(1.0./4.0)+U1.*l.*m2.*t5.*t8.*(1.0./2.0);0.0];
