function B_IM = B(dq1,dq2,dq3,g,l,m2,q1,q2,tau)
%B
%    B_IM = B(DQ1,DQ2,DQ3,G,L,M2,Q1,Q2,TAU)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    02-Oct-2020 17:51:13

t2 = q1-q2;
t3 = sin(t2);
t4 = dq1.^2;
t5 = sin(q1);
t6 = dq2.^2;
t7 = sin(q2);
B_IM = [dq1;dq2;dq3;tau-l.*m2.*(g.*t5.*3.0+l.*t3.*t6).*(1.0./2.0);-tau-l.*m2.*(g.*t7-l.*t3.*t4).*(1.0./2.0);l.*m2.*(t4.*t5.*3.0+t6.*t7).*(1.0./2.0);-dq1.*l.*t3.*(dq1-dq2)];
