function dq_itu = dq_itu_Gibbs(U1,U2,U3,U4,U5,U6,U7,q2,q3)
%DQ_ITU_GIBBS
%    DQ_ITU = DQ_ITU_GIBBS(U1,U2,U3,U4,U5,U6,U7,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    07-Oct-2020 06:53:26

t2 = cos(q2);
t3 = 1.0./t2;
t4 = cos(q3);
t5 = sin(q3);
t6 = sin(q2);
dq_itu = [U2.*t3.*t5+U3.*t3.*t4;U2.*t4-U3.*t5;U1+U2.*t3.*t5.*t6+U3.*t3.*t4.*t6;U4;U5;U6;U7];
