function T = Energy_Gibbs(Ixx,Ixy,Ixz,Iyy,Iyz,Izz,U1,U2,U3,U4,U5,U6,U7,a,l,m,m_sat,q1,q2,q3,q4)
%ENERGY_GIBBS
%    T = ENERGY_GIBBS(IXX,IXY,IXZ,IYY,IYZ,IZZ,U1,U2,U3,U4,U5,U6,U7,A,L,M,M_SAT,Q1,Q2,Q3,Q4)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    07-Oct-2020 06:53:25

t2 = cos(q2);
t4 = cos(q1);
t5 = sin(q1);
t8 = sin(q2);
t3 = U2.*a.*2.0+U2.*l+U2.*q4.*2.0-U7.*t8.*2.0+U5.*t2.*t4.*2.0+U6.*t2.*t5.*2.0;
t6 = sin(q3);
t7 = cos(q3);
t9 = U4+U5.*t5.*t6-U6.*t4.*t6+U7.*t2.*t7+U5.*t4.*t7.*t8+U6.*t5.*t7.*t8;
t10 = U1.*a.*2.0+U1.*l+U1.*q4.*2.0-U7.*t2.*t6.*2.0+U5.*t5.*t7.*2.0-U6.*t4.*t7.*2.0-U5.*t4.*t6.*t8.*2.0-U6.*t5.*t6.*t8.*2.0;
T = Ixx.*U1.^2.*(1.0./2.0)+Iyy.*U2.^2.*(1.0./2.0)+Izz.*U3.^2.*(1.0./2.0)+U5.^2.*m_sat.*(1.0./2.0)+U6.^2.*m_sat.*(1.0./2.0)+U7.^2.*m_sat.*(1.0./2.0)+m.*t3.^2.*(1.0./8.0)+m.*t9.^2.*(1.0./2.0)+m.*t10.^2.*(1.0./8.0)-Ixy.*U1.*U2-Ixz.*U1.*U3-Iyz.*U2.*U3;
