function M_g = M_gibss(Ixx,Ixy,Ixz,Iyy,Iyz,Izz,a,l,m,m_sat,q1,q2,q3,q4)
%M_GIBSS
%    M_G = M_GIBSS(IXX,IXY,IXZ,IYY,IYZ,IZZ,A,L,M,M_SAT,Q1,Q2,Q3,Q4)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    07-Oct-2020 06:53:24

t3 = l.*(1.0./2.0);
t2 = a+q4+t3;
t4 = cos(q1);
t5 = cos(q3);
t6 = sin(q1);
t7 = sin(q2);
t8 = sin(q3);
t9 = t2.^2;
t10 = m.*t9;
t11 = cos(q2);
t12 = t5.*t6;
t13 = t12-t4.*t7.*t8;
t14 = m.*t2.*t13;
t15 = m.*t2.*t4.*t11;
t16 = m.*t6.*t8;
t17 = m.*t4.*t5.*t7;
t18 = t16+t17;
t19 = t4.*t5;
t20 = t6.*t7.*t8;
t21 = t19+t20;
t22 = m.*t2.*t6.*t11;
t23 = m.*t5.*t6.*t7;
t24 = t23-m.*t4.*t8;
t25 = m+m_sat;
t26 = m.*t5.*t11;
M_g = reshape([Ixx+t10,-Ixy,-Ixz,0.0,t14,-m.*t2.*t21,-m.*t2.*t8.*t11,-Ixy,Iyy+t10,-Iyz,0.0,t15,t22,-m.*t2.*t7,-Ixz,-Iyz,Izz,0.0,0.0,0.0,0.0,0.0,0.0,0.0,m,t18,t24,t26,t14,t15,0.0,t18,t25,0.0,0.0,-m.*t2.*t21,t22,0.0,t24,0.0,t25,0.0,-m.*t2.*t8.*t11,-m.*t2.*t7,0.0,t26,0.0,0.0,t25],[7,7]);
