function Ptot = ptot_Gibbs(U1,U2,U3,U4,U5,U6,U7,a,l,m,m_sat,q1,q2,q3,q4)
%PTOT_GIBBS
%    PTOT = PTOT_GIBBS(U1,U2,U3,U4,U5,U6,U7,A,L,M,M_SAT,Q1,Q2,Q3,Q4)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    07-Oct-2020 06:53:26

t2 = sin(q1);
t3 = sin(q3);
t4 = t2.*t3;
t5 = cos(q1);
t6 = cos(q3);
t7 = sin(q2);
t8 = t5.*t6.*t7;
t9 = t4+t8;
t10 = t2.*t6;
t28 = t3.*t5.*t7;
t11 = t10-t28;
t12 = cos(q2);
t13 = 1.0./t12;
t14 = U3.*t6.*t13;
t15 = U2.*t3.*t13;
t16 = t14+t15;
t17 = l.*(1.0./2.0);
t18 = a+q4+t17;
t19 = t3.*t5;
t22 = t2.*t6.*t7;
t20 = t19-t22;
t21 = U5.*t9;
t23 = U7.*t6.*t12;
t46 = U6.*t20;
t24 = U4+t21+t23-t46;
t25 = t5.*t6;
t26 = t2.*t3.*t7;
t27 = t25+t26;
t29 = U5.*t11;
t30 = U3.*t6.*t7.*t13;
t31 = U2.*t3.*t7.*t13;
t48 = t7.*t16;
t32 = U1+t30+t31-t48;
t33 = t18.*t32;
t47 = U6.*t27;
t49 = U7.*t3.*t12;
t34 = t29+t33-t47-t49;
t35 = U3.*t3;
t42 = U2.*t6;
t36 = t35-t42;
t37 = t6.*t36;
t43 = t3.*t12.*t16;
t38 = t37-t43;
t39 = t18.*t38;
t40 = U7.*t7;
t44 = U5.*t5.*t12;
t45 = U6.*t2.*t12;
t41 = t39+t40-t44-t45;
Ptot = [U5.*m_sat+m.*(t9.*t24+t11.*t34-t5.*t12.*t41);U6.*m_sat-m.*(t20.*t24+t27.*t34+t2.*t12.*t41);U7.*m_sat+m.*(t7.*t41+t6.*t12.*t24-t3.*t12.*t34)];
