function A_ = A_Voltra(l,m1,m2,q1,q2)
%A_VOLTRA
%    A_ = A_VOLTRA(L,M1,M2,Q1,Q2)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    03-Oct-2020 21:52:26

t2 = q1.*2.0;
t3 = q2.*2.0;
t4 = t2-t3;
t5 = cos(t4);
A_ = (l.^2.*m2.*(m1.*-9.6e1-m2.*1.14e2+m1.*t5.*3.2e1+m2.*t5.*3.4e1+m2.*cos(t2).*7.5e1-m2.*cos(t3).*3.0e1+m2.*cos(q2.*-4.0+t2).*3.0).*(-1.0./4.8e1))./((m1+m2.*2.0).*(t5+cos(q1-q2).*4.0+3.0));
