function M21 = M21_Voltra(l,m2,q1,q2)
%M21_VOLTRA
%    M21 = M21_VOLTRA(L,M2,Q1,Q2)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    03-Oct-2020 21:52:29

M21 = [l.*m2.*cos(q1).*(3.0./2.0),l.*m2.*cos(q2).*(1.0./2.0)];
