function M22 = M22_Voltra(m1,m2)
%M22_VOLTRA
%    M22 = M22_VOLTRA(M1,M2)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    03-Oct-2020 21:52:29

M22 = m1+m2.*2.0;
