function PXYZ = PXYZ_Voltra(dq1,dq2,dq3,l,m1,m2,q1,q2)
%PXYZ_VOLTRA
%    PXYZ = PXYZ_VOLTRA(DQ1,DQ2,DQ3,L,M1,M2,Q1,Q2)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    03-Oct-2020 21:52:29

PXYZ = [dq3.*m1+m2.*(dq3.*2.0+dq1.*l.*cos(q1).*(3.0./2.0)+dq2.*l.*cos(q2).*(1.0./2.0));l.*m2.*(dq1.*sin(q1).*3.0+dq2.*sin(q2)).*(1.0./2.0);0.0];
