function Ptot = Lmoment(px,py,pz)
%LMOMENT
%    PTOT = LMOMENT(PX,PY,PZ)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    26-Aug-2020 09:59:19

Ptot = [px;py;pz];
