function M_ = A(Ixx,Ixy,Ixz,Iyy,Iyz,Izz,a,l,m,m_sat,q1,q2,q3,q4)
%A
%    M_ = A(IXX,IXY,IXZ,IYY,IYZ,IZZ,A,L,M,M_SAT,Q1,Q2,Q3,Q4)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    07-Oct-2020 06:47:11

t2 = cos(q2);
t3 = sin(q2);
t4 = cos(q3);
t5 = sin(q3);
t6 = a.^2;
t7 = l.^2;
t8 = q4.^2;
t9 = sin(q1);
t10 = cos(q1);
t11 = a.*m.*t4.*t9;
t12 = l.*m.*t4.*t9.*(1.0./2.0);
t13 = m.*q4.*t4.*t9;
t14 = t11+t12+t13-a.*m.*t3.*t5.*t10-l.*m.*t3.*t5.*t10.*(1.0./2.0)-m.*q4.*t3.*t5.*t10;
t15 = m.*t5.*t9;
t16 = m.*t3.*t4.*t10;
t17 = t15+t16;
t18 = -a.*m.*t4.*t10-l.*m.*t4.*t10.*(1.0./2.0)-m.*q4.*t4.*t10-a.*m.*t3.*t5.*t9-l.*m.*t3.*t5.*t9.*(1.0./2.0)-m.*q4.*t3.*t5.*t9;
t19 = m.*t3.*t4.*t9;
t20 = t19-m.*t5.*t10;
t21 = m+m_sat;
t22 = -a.*m.*t2.*t5-l.*m.*t2.*t5.*(1.0./2.0)-m.*q4.*t2.*t5;
t23 = m.*t2.*t4;
M_ = reshape([-Ixx.*t3-Ixy.*t2.*t5-Ixz.*t2.*t4-m.*t3.*t6-m.*t3.*t7.*(1.0./4.0)-m.*t3.*t8-a.*l.*m.*t3-a.*m.*q4.*t3.*2.0-l.*m.*q4.*t3,Ixy.*t3+Iyy.*t2.*t5-Iyz.*t2.*t4+m.*t2.*t5.*t6+m.*t2.*t5.*t7.*(1.0./4.0)+m.*t2.*t5.*t8+a.*l.*m.*t2.*t5+a.*m.*q4.*t2.*t5.*2.0+l.*m.*q4.*t2.*t5,Ixz.*t3-Iyz.*t2.*t5+Izz.*t2.*t4,0.0,a.*m.*t5.*t10+l.*m.*t5.*t10.*(1.0./2.0)+m.*q4.*t5.*t10-a.*m.*t3.*t4.*t9-l.*m.*t3.*t4.*t9.*(1.0./2.0)-m.*q4.*t3.*t4.*t9,a.*m.*t5.*t9+l.*m.*t5.*t9.*(1.0./2.0)+m.*q4.*t5.*t9+a.*m.*t3.*t4.*t10+l.*m.*t3.*t4.*t10.*(1.0./2.0)+m.*q4.*t3.*t4.*t10,0.0,-Ixy.*t4+Ixz.*t5,Iyy.*t4+Iyz.*t5+m.*t4.*t6+m.*t4.*t7.*(1.0./4.0)+m.*t4.*t8+a.*l.*m.*t4+a.*m.*q4.*t4.*2.0+l.*m.*q4.*t4,-Iyz.*t4-Izz.*t5,0.0,a.*m.*t2.*t4.*t10+l.*m.*t2.*t4.*t10.*(1.0./2.0)+m.*q4.*t2.*t4.*t10,a.*m.*t2.*t4.*t9+l.*m.*t2.*t4.*t9.*(1.0./2.0)+m.*q4.*t2.*t4.*t9,-a.*m.*t3.*t4-l.*m.*t3.*t4.*(1.0./2.0)-m.*q4.*t3.*t4,Ixx+m.*t6+m.*t7.*(1.0./4.0)+m.*t8+a.*l.*m+a.*m.*q4.*2.0+l.*m.*q4,-Ixy,-Ixz,0.0,t14,t18,t22,0.0,0.0,0.0,m,t17,t20,t23,t14,a.*m.*t2.*t10+l.*m.*t2.*t10.*(1.0./2.0)+m.*q4.*t2.*t10,0.0,t17,t21,0.0,0.0,t18,a.*m.*t2.*t9+l.*m.*t2.*t9.*(1.0./2.0)+m.*q4.*t2.*t9,0.0,t20,0.0,t21,0.0,t22,-a.*m.*t3-l.*m.*t3.*(1.0./2.0)-m.*q4.*t3,0.0,t23,0.0,0.0,t21],[7,7]);
